::Const.FactionTrait.Actions[::Const.FactionTrait.Beasts].extend([
	"scripts/factions/actions/beasts/cp_build_direwolves_camp_action",
	"scripts/factions/actions/beasts/cp_build_ghouls_camp_action",
	"scripts/factions/actions/beasts/cp_build_hyena_camp_action",
	"scripts/factions/actions/beasts/cp_build_lindwurm_camp_action",
	"scripts/factions/actions/beasts/cp_build_serpent_camp_action",
	"scripts/factions/actions/beasts/cp_build_unhold_bog_camp_action",
	"scripts/factions/actions/beasts/cp_build_unhold_camp_action",
	"scripts/factions/actions/beasts/cp_build_unhold_frost_camp_action",
	"scripts/factions/actions/beasts/cp_build_webknecht_camp_action",
]);
